[build]
  publish = "dist/public"
  command = "vite build && mkdir -p netlify/functions && npx esbuild netlify/functions/generate-script.ts --bundle --platform=node --outfile=netlify/functions/generate-script.js --external:@google/genai"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"